version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sprintproject3/SprintProject-persistent
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
    - location: scripts/scripts/start_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
    
  
  