version: "3.9"  # optional since v1.27.0
services:
  app:
    container_name: nodeimage
    restart: always 
    build: ./
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
